version: "3.9"

name: myapi

services:
  api:
    build:
      context: ./todo
      dockerfile: Dockerfile.dev
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"  # Expose container port 8000 to host port 8000
    networks:
      - my-api-net
    environment:
      - DATABASE_HOST=postgres_db
      - DATABASE_PORT=5432
      - POSTGRES_USER=abdulqadir
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase

  postgres_db:
    image: postgres:latest  # Use the official PostgreSQL image
    restart: always
    container_name: PostgresCont
    environment:
      - POSTGRES_USER=abdulqadir
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=mydatabase
    ports:
      - '5433:5432'
    volumes:
      - my_postgres_db:/var/lib/postgresql/data
    networks:
      - my-api-net

volumes:
  my_postgres_db:
    driver: local

networks:
  my-api-net:  # Define the custom network
