# Define the name of the Docker Compose application
name: "myapi"

# Specify the version of the Docker Compose file format
version: '3.9'

# Define the services (containers) that make up the application
services:
  api:  # Define a service named "api"
    build:  # Configuration for building the Docker image
      context: ./helloworld  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of the Dockerfile (assumes it's named 'Dockerfile')
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container